spring:
  application:
    name: adminUsuario

  cloud:
    loadbalancer:
      enabled: true
  datasource:
    url: jdbc:sqlserver://192.168.10.4:50037;databaseName=SATA;encrypt=true;trustServerCertificate=true
    username: CNX_SASIP
    password: SOh*OfJ*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none # No cambiar el esquema automáticamente
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true # Opcional, para mostrar las consultas en logs


server:
  port: 0
  servlet:
    context-path: /api

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/