spring:
  application:
    name: gateway

  profiles:
    active: auth2 
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2



server:
  port: 4040 # Puerto donde corre el gateway

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway" # Incluye los endpoints de salud, info y gateway
  endpoint:
    health:
      show-details: always # Muestra los detalles completos en el estado de salud
    gateway:
      access: unrestricted # Control de acceso a los endpoints del gateway